[package]
name = "Puzla"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.23.14"
rand = "0.8"
ordered-float = "1.0"
rayon = "1.5.0"
